import Image from 'next/image'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24 max-w-[1000px] m-auto">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu feugiat pretium nibh ipsum consequat nisl. Viverra accumsan in nisl nisi scelerisque. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Massa tincidunt dui ut ornare lectus sit amet est. Mattis rhoncus urna neque viverra justo. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Id cursus metus aliquam eleifend mi. Volutpat odio facilisis mauris sit amet. Magna eget est lorem ipsum dolor sit. Nibh sit amet commodo nulla facilisi nullam. Tempor id eu nisl nunc mi ipsum. Sodales ut eu sem integer vitae justo eget.

Massa eget egestas purus viverra accumsan in nisl. Volutpat ac tincidunt vitae semper quis lectus nulla. Duis ultricies lacus sed turpis tincidunt id aliquet. Id semper risus in hendrerit gravida. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Felis imperdiet proin fermentum leo vel. Non nisi est sit amet. Nec ultrices dui sapien eget mi. Id faucibus nisl tincidunt eget nullam non nisi est sit. Lectus urna duis convallis convallis tellus id interdum. Tellus orci ac auctor augue mauris. Eu sem integer vitae justo eget magna fermentum. Diam quis enim lobortis scelerisque fermentum. Nunc id cursus metus aliquam eleifend mi in nulla. Imperdiet dui accumsan sit amet. Tempus urna et pharetra pharetra massa massa. Tellus mauris a diam maecenas.

Urna nunc id cursus metus aliquam eleifend mi. Cras tincidunt lobortis feugiat vivamus at augue eget. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Pretium nibh ipsum consequat nisl vel pretium lectus. Sed tempus urna et pharetra pharetra. Est ante in nibh mauris cursus mattis molestie a. Gravida in fermentum et sollicitudin ac. Pellentesque elit eget gravida cum sociis natoque penatibus. Fusce id velit ut tortor pretium viverra suspendisse potenti nullam. Vitae purus faucibus ornare suspendisse sed nisi lacus sed.

Id consectetur purus ut faucibus pulvinar elementum integer. Eu lobortis elementum nibh tellus. Sed turpis tincidunt id aliquet risus feugiat in. Risus nec feugiat in fermentum posuere urna nec tincidunt. Vitae suscipit tellus mauris a diam maecenas. Gravida arcu ac tortor dignissim convallis aenean. Amet dictum sit amet justo donec enim. Risus nec feugiat in fermentum. Risus ultricies tristique nulla aliquet enim. Sed turpis tincidunt id aliquet risus feugiat in. Fringilla est ullamcorper eget nulla. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Lorem dolor sed viverra ipsum nunc.

Aliquam sem fringilla ut morbi tincidunt augue. Eget nulla facilisi etiam dignissim diam quis. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Eget nulla facilisi etiam dignissim. Bibendum est ultricies integer quis. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Purus sit amet volutpat consequat mauris nunc congue nisi. Sit amet justo donec enim. At varius vel pharetra vel turpis nunc. Amet risus nullam eget felis. Ipsum a arcu cursus vitae congue mauris rhoncus aenean vel. Neque ornare aenean euismod elementum nisi quis eleifend quam.</p>
    </main>
  )
}
